arb-dir: lib/src/common/services/localization/l10n
template-arb-file: app_en.arb
output-localization: app_localizations.dart
output-dir: lib/src/common/services/localization
output-class: AppLocalizations
nullable-getter: false
synthetic-package: false