name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  glass_kit: ^3.0.0
  intl: ^0.18.1
  meta: ^1.10.0
  shared_preferences: ^2.2.2
  yandex_mapkit: ^3.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/weathers/
    - assets/icons/

  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overpass-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overpass-Black.ttf
          weight: 900
        - asset: assets/fonts/Overpass-Light.ttf
          weight: 300
