name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  yandex_mapkit: ^3.3.3
  geolocator: ^10.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/weathers/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overpass-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overpass-Black.ttf
          weight: 900
        - asset: assets/fonts/Overpass-Light.ttf
          weight: 300

